name: Chef Tells
favicon: null
layout_spectrum: 0.08822333812713623
typography_spectrum: 0.9015191483777016
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.21661875559948385
  lightness: 0.4347807152662426
  saturation: 0.5884260127786547
  rhythmicContrast: 0.40544373728334904
purpose: []
